### ISSUE TITLE
保证函数⼀定可以收敛到最低点

### ISSUE THREAD

**Issue by WZURocsky** [Jinqi-J/Numerical-Optimization-in-Robotics-Homework#1]
我有一个疑问想请教请教，提供的文件里面的course2内的report.pdf第五页所讲的“保证函数⼀定可以收敛到最低点“这句话的意思是指它一定可以收敛到非凸但光滑函数的全局最优解吗？还是指的局部最优解呢？

**Comment by Jinqi-J** [comment]
局部最优解
